### PR TITLE
Enhance fetch user profile #113

### LINKED ISSUE #113: Enhance fetch user profile
### Enhance fetch user profile

Base: `main`
New branch: `sql-113-enhance-fetch-profile`

---

**Prerequisites**:

- [x] Finish reading the entire issue before beninging.

---

**Requirements**:

- Affected file: src/repositories/sql/users/`fetch_profile.sql`
- Add the following fields:
  - `likes_received`
    - A column alias for the total number of likes from all the posts made by the user
  - `views_received`
    - A column alias for the total number of views from all the posts made by the user

---

**Notes**:

- none

### PR DESCRIPTION
**Pull request by LyndonTomas**
Closes #113 

Still having issues on the other issue to I worked on this one first.

Screenshots:

Reference:
sample user reference

Query and Sample Output:

query sample and output

### CODE REVIEW

**Comment by jp-ong** [comment]
Looks good. May I see the result of this query:
```sql
SELECT post_id, user_id, views_count, likes_count FROM posts WHERE user_id = 7;
```

This is just to see the number of likes and views of each post before they were tallied.
Comment the screenshot.

**Comment by LyndonTomas** [comment]
> s is just to see the number of

It's in the image above. 
image

**Comment by jp-ong** [comment]
Side note.
Pull requests are automatically titled by GitHub.
However, title your pull request similar to what the title of the issue it's trying to resolve so that we can go back at any moment to the list of approved pull requests and determine our progress just by reading the title.
To start, edit this PR's title to be the exact same with #113.

**Comment by jp-ong** [comment]
> > This is just to see the number of likes and views of each post before they were tallied.
> > Comment the screenshot.
> 
> It's in the image above. image
> 
> Maybe the quality of the screenshot is a bit blurry, mb. But the output is likes_received being 1 and comments_received being 3 which matches the output of the sample query.

No. In that screenshot, the likes and views were already tallied. I'd like to see the numbers BEFORE that. List the posts made by user 7 with the query I mentioned.

**Comment by LyndonTomas** [comment]
> Side note. Pull requests are automatically titled by GitHub. However, title your pull request similar to what the title of the issue it's trying to resolve so that we can go back at any moment to the list of approved pull requests and determine our progress just by reading the title. To start, edit this PR's title to be the exact same with #113.

Done. I forgot about it. Thank you for reminding me.

**Comment by jp-ong** [comment]
Just execute the query and send the screenshot. Thanks.
**Query:**
```sql
SELECT post_id, user_id, views_count, likes_count FROM posts WHERE user_id = 7;
```
**Expected ouput would be similar to this:**
image

**Comment by LyndonTomas** [comment]
> Just execute the query and send the screenshot. Thanks. **Query:**
> 
> ```sql
> SELECT post_id, user_id, views_count, likes_count FROM posts WHERE user_id = 7;
> ```
> 
> **Expected ouput would be similar to this:** image

image

Here's the image.

**Review by jp-ong — APPROVED** [review]

**Pull request merged**
