### PR TITLE
Show offenses per offense type

### LINKED ISSUE #90: Show offenses per offense type
### Show offenses per offense type

Base: `main`
New branch: `sql-90-fetch-offenses`

---

**Prerequisites**:

- 

---

**Requirements**:

- 

---

**Notes**:

- you must show the offenses per offense_type
- make sure to show them in different .sql files.

### PR DESCRIPTION
**Pull request by LyndonTomas**
Closes #90

Show comments offenses:

shows comments offense

Show posts offenses:

shows posts offense

Show users offenses:
shows users offense

### CODE REVIEW

**Review by jp-ong — CHANGES_REQUESTED** [review]
- `show_users_offenses.sql` file is empty
- Use "fetch" instead of "show" for consistency
- Include ban time and offense id

**Comment by jp-ong** [comment]
Also rename branch to `sql-90-fetch-offenses`

**Comment by jp-ong** [comment]
> Also rename branch to `sql-90-fetch-offenses`

The number in branch names must reflect the issue it is targeting

**Comment by LyndonTomas** [comment]
Updated the branch as sql-90-fetch-offenses

**Pull request closed without merging**
