### PR TITLE
Add SQL commands for views and likes #112

### LINKED ISSUE #112: Add SQL commands for views and likes
### Add SQL commands for views and likes

Base: `main`
New branch: `sql-112-userpost-interaction`

---

**Prerequisites**:

- [x] Finish reading the entire issue before beninging.

---

**Requirements**:

- **User views a post**
  - Create an `INSERT INTO` command to `userpost` table given a `user_id` and `post_id`
  - Create a RULE that listens to the INSERT event to `userpost`
    - In this rule, if a `userpost` entry with the given `user_id` and `post_id` already exists, instruct the rule to **[DO INSTEAD NOTHING](https://www.postgresql.org/docs/9.1/sql-createrule.html)**.
    - If this rule conflicts with the existing `add_view`, integrate the logic of this new rule to `add_view` rule instead of creating a new one.
    - Purpose of this rule is to ensure that there are no duplicates.
- **User likes a post**
  - Create an `UPDATE` command to a `userpost` entry that matches a given `user_id` and `post_id` to update its `is_liked` value to **TRUE**.
  - Update the `updated_at` value as well.
- **Check if user liked the post**
  - Create a `SELECT` command to fetch the `userpost` entry with a given `user_id` and `post_id`
    - Return all fields
- **ADDITIONAL**
  - Rename the current rules
    - add_view -> count_views
    - add_like -> count_likes
    - add_comments -> count_comments
    - Make the changes to these two files:
      - src/repositories/sql/`rules.sql`
      - src/repositories/sql/`create.sql`

---

**Notes**:

- Look into [**TRIGGER**](https://www.postgresql.org/docs/9.1/sql-createtrigger.html). Maybe it would fit this use case better, I'm not sure.

### PR DESCRIPTION
**Pull request by LyndonTomas**
Closes #112 

Status as of 1-20-22: In Progress

Testing inser_one.sql in /userpost:

TODO based from #112:
- [x] Create an INSERT INTO command to userpost table given a user_id and post_id
- [x] Create a RULE that listens to the INSERT event to userpost
- [x] Create an UPDATE command to a userpost entry that matches a given user_id and post_id to update its is_liked value to TRUE.
- [x] Create a SELECT command to fetch the userpost entry with a given user_id and post_id
- [x] Rename the current rules

### CODE REVIEW

**Comment by LyndonTomas** [comment]
Update: I have created the rule check_userpost.
It does what is requested from #112. 

The userpost table before the rule was added:
userpost before rule

Creating the rule and it's success feedback:
create rule query and output


Then I've tested the rule if it works by creating an INSERT INTO command
with values that already exist. And it didn't enter.
test rule query thru insert into command

Here is the post after the insert:
post after view


Here is the userpost after the rule creation and insert test:
userpost after the rule

**Comment by LyndonTomas** [comment]
Updates on the like_one.sql

userpost before liking:
userpost before liking

liking sample query:
liking sample query

post after liking:
post after liking

userpost after liking:
userpost after liking

**Comment by LyndonTomas** [comment]
Testing of functionality of each rule as of now.

**Comment by LyndonTomas** [comment]
I've tested the rules' functionality after renaming them in my own machine.

check_userpost
2nd test of check userpost


count_view
post before view
add view
post after view


count_likes
post before liking
liking syntax
post after liking


count_comments
post before and after comment

**Review by jp-ong — CHANGES_REQUESTED** [review]
Nice. Logic looks good.

---

Just a couple of inconsistencies that needs to be addressed.
- `add_like` rule must be `count_likes` - plural
- The name of the rules has not yet been updated for the DROP RULE commands

**Comment by LyndonTomas** [comment]
> Nice. Logic looks good.
> 
> Just a couple of inconsistencies that needs to be addressed.
> 
> * `add_like` rule must be `count_likes` - plural
> * The name of the rules has not yet been updated for the DROP RULE commands

Oh, yes, I forgot to address this last night. Thank you for addressing them.

**Review by jp-ong — CHANGES_REQUESTED** [review]
Add new rule to DROP RULE commands

**Review by jp-ong — APPROVED** [review]
Nice boi

**Pull request merged**
