### PR TITLE
Add create table sql commands

### LINKED ISSUE #9: Add create table SQL commands
From `main` branch, **checkout** to a new branch and name it `sql-<>-create-table-commands`

---

**To-dos:**
- Add SQL commands for creating the following tables:
  - permissions
  - usertypes
  - posts
  - comments
  - userpost
  - poststatus
  - reports
  - bans
  - offenses
- Include `updated_at` field for all tables
- Update the command for `users` create table to include `usertypes` as foreign key

---

**Note:**
- **preferences** table has been removed
- place your commands in `_table.sql` file inside their respective folders
- name the folder similar to the table name (ie, `../users/_table.sql` or `../posts/_table.sql`)
- follow the **contraints** (ie, `UNIQUE`, `NOT NULL`, `DEFAULT ...`)

### PR DESCRIPTION
**Pull request by LyndonTomas**
Attempt that fixes #9 

Also, I added preferences since it was a foreign key in one of the tables.

### CODE REVIEW

**Review by jp-ong — CHANGES_REQUESTED** [review]
Nice, better 👍 

✔️ offenses
✔️ permissions
✔️ posts
✔️ reports
✔️ userpost
✔️ users
❌ bans
❌ comments
❌ poststatus
❌ usertypes
❌ preferences

---

**bans**
- Invalid `FOREIGN KEY` syntax still present

**poststatus**
- Check `status_id` data type

**comments**
- Fix spacing after `post_id`

**usertypes**
- Check `usertype_id`, `permission_id` data type

**preferences**
- You can safely delete this since it looks like `users` is not using this as reference

---
Note:
- I'm expecting 1 commit per table, total 5, for the next update. tenks

**Comment by LyndonTomas** [comment]
I changed most of the requests, I just don't follow the comments spacing. Kindly elaborate, thank you.

**Comment by jp-ong** [comment]
> I changed most of the requests, I just don't follow the comments spacing. Kindly elaborate, thank you.

Add missing space after `post_id` in `comments` table...
Also, for consistency and to follow convention, avoid past tense in commit messages.

**Review by jp-ong — APPROVED** [review]
Looks good to me

**Review by jp-ong — APPROVED** [review]

**Pull request merged**
