### PR TITLE
Populate offenses table

### LINKED ISSUE #81: Populate offenses table
### Populate offenses table

Base: `main`
New branch: `sql-81-populate-offenses`

---

**Prerequisites**:

- 

---

**Requirements**:

- Insert a file named `_data.sql`

---

**Notes**:

- Base the offenses from the thesis (docs).

### PR DESCRIPTION
**Pull request by LyndonTomas**
Closes #81

So the offenses are 3 sets due to offense_type.

### CODE REVIEW

**Review by jp-ong — CHANGES_REQUESTED** [review]
- [ ] Use [**Title case**](https://en.wikipedia.org/wiki/Title_case) for the offense titles.
  - Use this [**tool**](https://www.titlecase.com/) if you're unsure of how to convert to title case.
- [ ] Remove periods at the end of titles.
- [ ] Don't shorten "or" to "/".
  - "Any act/form..." must be
  - "**Any Act or Form**"
- [ ] I think the use of "and/or" is unnecessary as "or" includes the cases where "and" would be true.
  - "Recruiting to any fraternities and/or sororities." must be 
  - "**Recruiting to Any Fraternities or Sororities**"
  - _Any counter arguments for this one? I'm not so sure myself._

**Comment by LyndonTomas** [comment]
> * [ ]  Use [**Title case**](https://en.wikipedia.org/wiki/Title_case) for the offense titles.
>   
>   * Use this [**tool**](https://www.titlecase.com/) if you're unsure of how to convert to title case.
> * [ ]  Remove periods at the end of titles.
> * [ ]  Don't shorten "or" to "/".
>   
>   * "Any act/form..." must be
>   * "**Any Act or Form**"
> * [ ]  I think the use of "and/or" is unnecessary as "or" includes the cases where "and" would be true.
>   
>   * "Recruiting to any fraternities and/or sororities." must be
>   * "**Recruiting to Any Fraternities or Sororities**"
>   * _Any counter arguments for this one? I'm not so sure myself._

Noted, thank you for your review. Will resolve in my next upload.

**Comment by jp-ong** [comment]
Also, as mentioned before, use `\x on` sparingly.
There's only 6 columns to display, and `created_at` and `updated_at` aren't even needed in the screenshot so you can just omit those if the row is too long.

Here's a hint:
```sql
SELECT offense_id, offense_title, offense_type, ban_time FROM offenses;
```

**Comment by jp-ong** [comment]
I just thought of something.
Since it's going to be tedious to keep track of the offense_id...
Why not create an `offense_code` column?

- Add another column to offenses table
- Name the column `offense_code`
- Constraints: `CHAR(3) NOT NULL UNIQUE`
- Give the offenses their own codes.
  - `P01` (post zero one) = first offense in the list that is applicable to a post
  - `U02` (user zero two) = second offense in the list that is applicable to a user
  - Or maybe, `P11` for the first post minor offense, `P21` for the first post major offense?

**Comment by LyndonTomas** [comment]
> oing to be tedious to keep

This is actually a great idea so that we could actually better distinguish the offenses. I was actually wondering where was I supposed to add the '8.1.etc' codes.

**Comment by LyndonTomas** [comment]
offenses

I've also added offense_code in the query. Thank you for your input.

**Review by jp-ong — APPROVED** [review]
yes

**Pull request merged**
